# Generated by Django 5.2.12 on 2026-04-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        ('shops', '0005_seed_subscription_plans'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', 'is_active', '-created_at'], name='products_pr_shop_id_1a7c98_idx'),
        ),
    ]
