# Generated by Django 5.2.12 on 2026-04-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='scarcity_text',
            field=models.CharField(blank=True, help_text='Optional urgency line, e.g. few items left.', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='social_proof_text',
            field=models.CharField(blank=True, help_text='Optional social proof line for the product card.', max_length=120),
        ),
    ]
