# Generated by Django 5.2.12 on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_product_slug"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_shop_id_1a7c98_idx",
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["shop", "is_active", "sort_order", "-created_at"],
                name="products_pr_shop_act_sort_idx",
            ),
        ),
    ]
