# Generated by Django 5.2.12 on 2026-04-06 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initdata_idempotency_shop_owner_unique'),
        ('products', '0002_initial'),
        ('shops', '0005_seed_subscription_plans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shop', '-created_at'], name='orders_orde_shop_id_3eea06_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'shop'], name='orders_orde_status_3f6d1c_idx'),
        ),
    ]
