# Generated by Django 5.2.12 on 2026-04-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=40)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('source', models.CharField(choices=[('landing_modal', 'Landing modal'), ('landing_sticky', 'Landing sticky CTA'), ('landing_hero', 'Landing hero'), ('landing_final', 'Landing final CTA')], default='landing_modal', max_length=32)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('referrer', models.CharField(blank=True, max_length=512)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Landing arizasi',
                'verbose_name_plural': 'Landing arizalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
