# Generated by Django 5.2.12 on 2026-04-06 06:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shop',
            constraint=models.UniqueConstraint(fields=('owner',), name='shops_shop_owner_uniq'),
        ),
    ]
