# Generated by Django 5.2.12 on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0010_shop_payment_note"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="subscriptionpayment",
            index=models.Index(
                fields=["status", "-created_at"],
                name="shops_spay_st_crtd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionpayment",
            index=models.Index(
                fields=["shop", "status"],
                name="shops_spay_shop_st_idx",
            ),
        ),
    ]
