# Generated by Django 5.2.12 on 2026-04-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_subscriptionpayment_list_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='channel',
            field=models.CharField(choices=[('manual_screenshot', 'Manual screenshot'), ('telegram', 'Telegram invoice')], db_index=True, default='manual_screenshot', max_length=32),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='invoice_chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='invoice_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='invoice_payload',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Telegram invoice payload (unique per pending payment).', max_length=128),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='telegram_payment_charge_id',
            field=models.CharField(blank=True, help_text='successful_payment.telegram_payment_charge_id', max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='telegram_provider_payment_charge_id',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='subscription_payments/'),
        ),
    ]
