# Generated by Django 5.2.12 on 2026-04-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_seller_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramWebhookDedup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.BigIntegerField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Telegram webhook update',
                'verbose_name_plural': 'Telegram webhook updates',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('admin', 'Admin'), ('platform_owner', 'Platform owner')], default='buyer', max_length=16),
        ),
        migrations.CreateModel(
            name='BotOnboardingQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True)),
                ('day', models.DateField(db_index=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Bot onboarding quota',
                'verbose_name_plural': 'Bot onboarding quotas',
                'constraints': [models.UniqueConstraint(fields=('chat_id', 'day'), name='uniq_bot_onboarding_quota_chat_day')],
            },
        ),
    ]
